// <auto-generated />
namespace P1_Clinic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class firstVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "202509181128337_firstVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
