//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Local", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Diagnosis , Prescription , And History.
        /// </summary>
        internal static string AccessDiagnosis_Prescription_AndHistory {
            get {
                return ResourceManager.GetString("AccessDiagnosis,Prescription,AndHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddMedicalRecord.
        /// </summary>
        internal static string AddMedicalRecord {
            get {
                return ResourceManager.GetString("AddMedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNewDoctor.
        /// </summary>
        internal static string AddNewDoctor {
            get {
                return ResourceManager.GetString("AddNewDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medical Record.
        /// </summary>
        internal static string AddNewMedicalRecord {
            get {
                return ResourceManager.GetString("AddNewMedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Patient.
        /// </summary>
        internal static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Payment.
        /// </summary>
        internal static string AddNewPayment {
            get {
                return ResourceManager.GetString("AddNewPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment.
        /// </summary>
        internal static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Prescription.
        /// </summary>
        internal static string AddPrescription {
            get {
                return ResourceManager.GetString("AddPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Have An Account.
        /// </summary>
        internal static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Paid.
        /// </summary>
        internal static string AlreadyPaid {
            get {
                return ResourceManager.GetString("AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        internal static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackToList.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Doctor Profile And Specialties.
        /// </summary>
        internal static string BrowseDoctorProfileAndSpecialies {
            get {
                return ResourceManager.GetString("BrowseDoctorProfileAndSpecialies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Clinic.
        /// </summary>
        internal static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Id.
        /// </summary>
        internal static string DoctorId {
            get {
                return ResourceManager.GetString("DoctorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Have An Account.
        /// </summary>
        internal static string DoNotHaveAnAccount {
            get {
                return ResourceManager.GetString("DoNotHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        internal static string Dosage {
            get {
                return ResourceManager.GetString("Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterAddress.
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterName.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterPhone.
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        internal static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        internal static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterYourPassword.
        /// </summary>
        internal static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your User Name.
        /// </summary>
        internal static string EnterYourUserName {
            get {
                return ResourceManager.GetString("EnterYourUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Patients , Doctors , Medical Records And More - All In One Place.
        /// </summary>
        internal static string ManagePatients_Doctors_MedicalRecordsAndMore_AllInOnePlace {
            get {
                return ResourceManager.GetString("ManagePatients,Doctors,MedicalRecordsAndMore-AllInOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payments.
        /// </summary>
        internal static string ManagePayments {
            get {
                return ResourceManager.GetString("ManagePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Record Id.
        /// </summary>
        internal static string MedicalRecordId {
            get {
                return ResourceManager.GetString("MedicalRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Records.
        /// </summary>
        internal static string MedicalRecords {
            get {
                return ResourceManager.GetString("MedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Name.
        /// </summary>
        internal static string MedicationName {
            get {
                return ResourceManager.GetString("MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Doctors Found Yet.
        /// </summary>
        internal static string NoDoctorsFoundYet {
            get {
                return ResourceManager.GetString("NoDoctorsFoundYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Medical Records Found Yet.
        /// </summary>
        internal static string NoMedicalRecordsFoundYet {
            get {
                return ResourceManager.GetString("NoMedicalRecordsFoundYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Patients Found Yet.
        /// </summary>
        internal static string NoPatientsFoundYet {
            get {
                return ResourceManager.GetString("NoPatientsFoundYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payments Found Yet.
        /// </summary>
        internal static string NoPaymentsFoundYet {
            get {
                return ResourceManager.GetString("NoPaymentsFoundYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        internal static string PatientDetails {
            get {
                return ResourceManager.GetString("PatientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay For Medical Records.
        /// </summary>
        internal static string PayForMedicalRecords {
            get {
                return ResourceManager.GetString("PayForMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        internal static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Id.
        /// </summary>
        internal static string PaymentId {
            get {
                return ResourceManager.GetString("PaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Id.
        /// </summary>
        internal static string PersonId {
            get {
                return ResourceManager.GetString("PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions.
        /// </summary>
        internal static string Prescriptions {
            get {
                return ResourceManager.GetString("Prescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Language.
        /// </summary>
        internal static string SelectALanguage {
            get {
                return ResourceManager.GetString("SelectALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Patient Payments And Billing Details.
        /// </summary>
        internal static string TrackPatientPaymentsAndBillingDetails {
            get {
                return ResourceManager.GetString("TrackPatientPaymentsAndBillingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Patient.
        /// </summary>
        internal static string UpdatePatient {
            get {
                return ResourceManager.GetString("UpdatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View And Manage All Patient Records Easily.
        /// </summary>
        internal static string ViewAndManageAllPatientRecordsEasily {
            get {
                return ResourceManager.GetString("ViewAndManageAllPatientRecordsEasily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View And Manage Prescribed Medications.
        /// </summary>
        internal static string ViewAndManagePrescribedMedications {
            get {
                return ResourceManager.GetString("ViewAndManagePrescribedMedications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Doctors.
        /// </summary>
        internal static string ViewDoctors {
            get {
                return ResourceManager.GetString("ViewDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewPatients.
        /// </summary>
        internal static string ViewPatients {
            get {
                return ResourceManager.GetString("ViewPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewPrescriptions.
        /// </summary>
        internal static string ViewPrescriptions {
            get {
                return ResourceManager.GetString("ViewPrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Records.
        /// </summary>
        internal static string ViewRecords {
            get {
                return ResourceManager.GetString("ViewRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitDescription.
        /// </summary>
        internal static string VisitDescription {
            get {
                return ResourceManager.GetString("VisitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Our Clinic.
        /// </summary>
        internal static string WelcomeToOurClinic {
            get {
                return ResourceManager.GetString("WelcomeToOurClinic", resourceCulture);
            }
        }
    }
}
